# credentials: postgres/example
version: '3.1'

services:
  postgres:
    image: postgres:9
    container_name: postgres
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=postgres
networks:
  default:
    external:
      name: cp-all-in-one_default